services:
    web:
        build: .
        command: flask run --host=0.0.0.0 --port=5000
        environment:
            FLASK_APP: "phasebook:create_app"
            FLASK_DEBUG: "TRUE"
        volumes:
            - .:/app
        ports:
            - "5000:5000"
